theme: jekyll-theme-minimal
title: [Personal Website by Niklas Leon Kluge]
description: [Welcome to my personal journey following my development at the Modern Japanese Program at Hokkaido University using Github and Jupyter Notebooks.]
logo: /assets/img/<logo_file>





