theme: jekyll-theme-minimal
title: [Personal Website by Niklas Leon Kluge]
description: [Welcome to my personal journey following my development at the Modern Japanese Program at Hokkaido University using Github and Jupyter Notebooks.]
logo: [https://user-images.githubusercontent.com/103370122/172084883-a37ce976-bd34-456a-ac61-4e5751ca38e4.png]





